// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJfqP0ikJQTbJgiZHD-9UzD4T6XN5Uxo',
    appId: '1:684701619738:web:629c3f44cbb7f7ae9d23a3',
    messagingSenderId: '684701619738',
    projectId: 'fiberguardbharat-a4465',
    authDomain: 'fiberguardbharat-a4465.firebaseapp.com',
    storageBucket: 'fiberguardbharat-a4465.appspot.com',
    measurementId: 'G-B3R7TMNLXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBEdgmMnaf1i4VcE1I6f8tlC9SwqQ2CQ',
    appId: '1:684701619738:android:c90f4a3bdc163f089d23a3',
    messagingSenderId: '684701619738',
    projectId: 'fiberguardbharat-a4465',
    storageBucket: 'fiberguardbharat-a4465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfJshsCvwWr3mEu6VYCPS8lVsRMONg5To',
    appId: '1:684701619738:ios:6859540dd45e2dca9d23a3',
    messagingSenderId: '684701619738',
    projectId: 'fiberguardbharat-a4465',
    storageBucket: 'fiberguardbharat-a4465.appspot.com',
    iosBundleId: 'com.example.fiberguardbharat',
  );
}
